# Generated by Django 6.0.7 on 2026-07-25 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_points', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waste_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to='collection_points.collectionpoint')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de capacidad',
                'verbose_name_plural': 'Registros de capacidad',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='ALTA', max_length=10)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('origin_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_origin', to='collection_points.collectionpoint')),
                ('reciclador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('target_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_target', to='collection_points.collectionpoint')),
            ],
            options={
                'verbose_name': 'Alerta logística',
                'verbose_name_plural': 'Alertas logísticas',
                'ordering': ['-created_at'],
            },
        ),
    ]
