# Generated by Django 6.0.7 on 2026-07-25 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(default='#2E7D32', max_length=7)),
            ],
            options={
                'verbose_name': 'Tipo de residuo',
                'verbose_name_plural': 'Tipos de residuo',
            },
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity_max', models.IntegerField(default=100)),
                ('capacity_current', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico'), ('INACTIVO', 'Inactivo')], default='NORMAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_points', to=settings.AUTH_USER_MODEL)),
                ('waste_types', models.ManyToManyField(related_name='points', to='collection_points.wastetype')),
            ],
            options={
                'verbose_name': 'Punto de reciclaje',
                'verbose_name_plural': 'Puntos de reciclaje',
            },
        ),
    ]
