# Generated by Django 6.0.7 on 2026-07-25 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_recyclingguide_category_difficulty_tips_reading_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎁', max_length=10)),
                ('category', models.CharField(choices=[('DESCUENTO', 'Descuento o Cupón'), ('PRODUCTO_ECO', 'Producto Ecológico'), ('CERTIFICADO', 'Reconocimiento Eco'), ('DONACION', 'Donación Ambiental')], default='DESCUENTO', max_length=30)),
                ('points_cost', models.IntegerField(default=100)),
                ('level_required', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['points_cost'],
            },
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['id'], 'verbose_name': 'Logro', 'verbose_name_plural': 'Logros'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('REPORTE', 'Reportes de Puntos'), ('RECICLAJE', 'Reciclaje & Novedades'), ('COMUNIDAD', 'Participación Ciudadana'), ('RACHA', 'Rachas Activas')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='achievement',
            name='points_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='xp_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('xp', models.IntegerField(default=0)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de puntos',
                'verbose_name_plural': 'Transacciones de puntos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('points_spent', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVO', max_length=20)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='gamification.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canje de recompensa',
                'verbose_name_plural': 'Canjes de recompensas',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
